<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Anush" failures="4" tests="20" name="org.runner.Runner" time="117.146" errors="1" timestamp="12 Jul 2020 11:00:40 GMT" skipped="0">
  <testcase classname="org.runner.Runner" name="runScenario" time="4.375">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.stepdefinition.Adactin_Login.user_is_navigating_to_BookingConfirm_page(Adactin_Login.java:170)
at ✽.User is navigating to BookingConfirm page(src/test/resources/features/AdactinMasterCard.feature:29)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="org.runner.Runner" name="runScenario" time="13.294"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="1.763"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="2.350">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.stepdefinition.Adactin_Login.user_is_navigating_to_BookingConfirm_page(Adactin_Login.java:170)
at ✽.User is navigating to BookingConfirm page(src/test/resources/features/Adactin_Login_Page.feature:29)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="org.runner.Runner" name="runScenario" time="2.741"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="4.103"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="14.918"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="12.578"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="5.997"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="4.451"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="3.997">
    <error message="Cannot locate an element using id=order_no
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;ANUSH&#039;, ip: &#039;192.168.1.3&#039;, os.name: &#039;Windows 8.1&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.3&#039;, java.version: &#039;14.0.1&#039;
Driver info: driver.version: RemoteWebDriver" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: Cannot locate an element using id=order_no
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ANUSH', ip: '192.168.1.3', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '14.0.1'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:327)
at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)
at org.openqa.selenium.By$ById.findElement(By.java:188)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at org.stepdefinition.Adactin_Login.user_get_the_booking_confirmation_order_no(Adactin_Login.java:183)
at ✽.User get the booking confirmation order no(src/test/resources/features/AdactinOtherCard.feature:37)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="org.runner.Runner" name="runScenario" time="4.281">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.stepdefinition.Adactin_Login.user_is_navigating_to_BookingConfirm_page(Adactin_Login.java:170)
at ✽.User is navigating to BookingConfirm page(src/test/resources/features/AdactinVisa.feature:29)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="org.runner.Runner" name="runScenario" time="13.021"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="5.796"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="5.943"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="4.383"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="3.357">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.stepdefinition.Adactin_Login.user_is_navigating_to_BookingConfirm_page(Adactin_Login.java:170)
at ✽.User is navigating to BookingConfirm page(src/test/resources/features/AdactinOtherCard.feature:29)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="org.runner.Runner" name="runScenario" time="4.745"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="2.548"/>
  <testcase classname="org.runner.Runner" name="runScenario" time="2.505"/>
</testsuite> <!-- org.runner.Runner -->
